DATABASE:
  ADDRESS:
  PORT:
  DBNAME:
  USERNAME:
  PASSWORD:
  USESSL:

TOWNY:
  CONVERSION:
  DATABASE:
    ADDRESS:
    PORT:
    DBNAME:
    USERNAME:
    PASSWORD:
    USESSL:

REBOOT:

MOTD:
  STABLE:
    LINE1: 'dsfsdf'
    LINE2: 'dsfsdfsdf'
  MAINTENANCE:
    LINE1: 'sdfsdfsd'
    LINE2: 'sfdfsdfs'
