name: EvitaOnline
version: 1.0
author: Ludwig Hornslied, OrigamiDream
main: com.tistory.hornslied.evitaonline.EvitaOnline
load: STARTUP

permissions:
  evitaonline.admin:
    default: false
  evitaonline.mod:
    default: false
  evitaonline.mayor:
    default: false
  evitaonline.vicemayor:
    default: false